commonsense_prob: 0.5
human_names_path: ./room_env/data/human-names
last_timestep: 128
maximum_num_locations_per_object: 3
maximum_num_objects_per_human: 4
maxiumum_days_period: 8
num_humans: 64
num_total_objects: 16
save_path: ./room_env/data/des-config-l-v2.json
seed: 42
semantic_knowledge_path: ./room_env/data/semantic-knowledge.json
